//src/app/layout.tsx

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Boxes } from "@/components/ui/background-boxes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "IIT - Bhilai E-voting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

<body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-slate-900`}>
        <div className="min-h-screen relative w-full overflow-hidden bg-slate-900 flex items-center justify-center p-4">
          <div className="absolute inset-0 w-full h-full bg-slate-900 z-20 [mask-image:radial-gradient(transparent,white)] pointer-events-none" />
          <div className="absolute inset-0">
            <Boxes />
          </div>
          <div className="relative z-30 w-full max-w-6xl mx-auto">
            {children}
          </div>
        </div>
      </body>

    </html>
  );
}